import type { Metadata } from "next";
import { Geist, Geist_Mono, K2D } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const K2d = K2D({
  variable: "--font-k2d-name",
  subsets: ["thai", "latin"],
  weight: ["500"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${K2d.variable} font-sans h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"> 
        <main>{children}</main>
        <Toaster position="top-center" />
        </body>
    </html>
  );
}
